### PR TITLE
Changing H2 in Navbar , add logo in correct size inside

### PR DESCRIPTION
**Pull request by basiazorychta**
Please check

### CODE REVIEW

**Review by jshortz — CHANGES_REQUESTED** [review]
Instead of having a series of &nbsp, might it be better to use margin-left or padding-left on the h2s? Would make editing later easier if we move it again for any reason.

**Comment by basiazorychta** [comment]
Yes. added - "col px-md-" branch updated

**Review by jshortz — APPROVED** [review]
LGTM

**Review by S-Sonal — APPROVED** [review]

**Comment by elmenqui** [comment]
Beautifu!

**Pull request merged**
